name: nodejs
displayName: NodeJS Runtime
description: Stack with NodeJS 12 blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah bla
tags: ["NodeJS", "Express", "ubi8"]
projectType: "nodejs"
language: "nodejs"
